Get sdk integration tests working with Spark
aqueducthq/aqueduct pull request #1190
Opened 2023-04-09 23:10 UTC by hsubbaraj-spiral

## Describe your changes and why you are making these changes
Modifies tests to work with Spark. Most of the changes involve adding a case in the test functions to use Pyspark Dataframe specific code. I also add the `pytest.mark.skip_for_spark_engines() `fixture to skip tests that don't work with Spark.
## Related issue number (if any)

## Loom demo (if any)

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [ ] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ ] If this is a new feature, I have added unit tests and integration tests.
- [ ] I have run the integration tests locally and they are passing.
- [ ] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [ ] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

2023-04-10 19:05 UTC, kenxu95 requested changes
Just a couple things I want to check on!

2023-04-10 19:05 UTC, kenxu95 commented on integration_tests/sdk/aqueduct_tests/test_functions/simple/model.py
> +        from pyspark.sql.functions import lit
Could you put a banner comment on top of this file explaining what the `lit` import does in the spark case? Not clear to me why it has to be a decimal value either.

2023-04-10 19:05 UTC, kenxu95 commented on src/golang/lib/job/spark.go
> +		HeartbeatTimeoutInSecond: 10,
I assume this was a necessary change to get it working with the test suite? This seems like quite a large numeric change - what are the ramifications of this?

2023-04-10 20:10 UTC, hsubbaraj-spiral commented on integration_tests/sdk/aqueduct_tests/checks_test.py
> +        check_artifact.get()
Yep this is correct!

2023-04-10 20:10 UTC, hsubbaraj-spiral commented on integration_tests/sdk/aqueduct_tests/checks_test.py
> +@pytest.mark.skip
Yes, should be converted to `@pytest.mark.skip_for_spark_engines()`

2023-04-10 20:14 UTC, hsubbaraj-spiral commented on integration_tests/sdk/conftest.py
> +            )
Ah this makes sense, was wondering how to hide the errors.

2023-04-11 17:21 UTC, kenxu95 approved these changes

2023-04-11 17:21 UTC, kenxu95 commented on integration_tests/sdk/aqueduct_tests/flow_test.py
> +@pytest.mark.skip_for_spark_engines(reason="requires implicit pandas requirement.")
my weird pet peeve/nit: Capitalize "requires"

2023-04-11 18:43 UTC, merged