Eng 1104 allow users to specify function specific
aqueducthq/aqueduct pull request #128
Opened 2022-06-22 00:21 UTC by Fanjia-Yan

This PR implements the following: 
1. Enable passing in `reqs` as a parameter for `op` which contain the absolute path of a file that specify the requirements to run the specific operator.

The file I changes:
1. `decorator.py`: enable the `op` to take in an extra param `reqs` and pass it in to `serialize_function()`
2. `utils.py`: if the the `reqs` passed in is `None`, nothing changes. If `reqs` is specified, if the path is valid, copy the file into the directory, else raise `FileNotFound` Error

I wrote some integration tests in previous commits but decided to delete it since the test I thought of was a bit trivial, what I wrote is that:
1. passed in a definitely not existing file path and assert it for FileNotFound Error,
3. passed in a requirements.txt from Sentiment Analysis and assert the completeness of the table

Looking for some suggestions!

2022-06-22 17:20 UTC, kenxu95 requested changes
The first test case you laid out was good. Give the operator a bad path and assert that you get the specific error back.

Other test cases I'd like to see are:
- Run an operator that uses a library not already installed in by the test suite.
1) Do the above for user defined requirements
2) Do the above for default requirements

2022-06-22 17:20 UTC, kenxu95 commented on sdk/aqueduct/decorator.py
> +            An absolute path to file that specify requirements for the specific
grammar nit: "specifies requirements for this specific operator"

2022-06-22 17:20 UTC, kenxu95 commented on sdk/aqueduct/utils.py
> +            An absolute path of file that specify the requirements of the operator.
but it can also be relative right? Like I can do `../sibling_dir/requirements.txt`

2022-06-22 17:20 UTC, kenxu95 commented on sdk/aqueduct/decorator.py
> +            An absolute path to file that specify requirements for the specific
Lets call this `reqs_path` for clarity.

2022-06-22 17:20 UTC, kenxu95 commented on sdk/aqueduct/utils.py
> +                "%s: requirements.txt file detected in user-provided directory, will not self-generate by inferring package dependencies."
not sure I get these comments, what do you mean by self-generate?

2022-06-22 17:20 UTC, kenxu95 commented on sdk/aqueduct/utils.py
> +            A path to file that specify requirements
nit: "specifies"

2022-06-23 16:43 UTC, Fanjia-Yan commented
Update the PR with the following changes:
1.change the naming `reqs` to `reqs_path`
2.edit grammar mistake in doc string and log console
3. Integration tests:
    -Provide @op() with a invalid path file, assert for FileNotFound Error
    -Create a default operator which its operation requires `transformers` package. During the execution of the operator, assert for AqueductError(inside it is moduleNotFound Error but show up as AqueductError)
    -Provide a operator with a valid path file to "requirements.txt". "requirements.txt" has `transformers` which the operator needs to execute. After execution, assert for the correctness of the dataframe from the outputartifact.get()

2022-06-27 18:08 UTC, kenxu95 approved these changes
A couple more comments I'd like to see addressed, but other than that looks good to me :D

2022-06-27 18:08 UTC, kenxu95 commented on integration_tests/sdk/requirement_test.py
> +)
I think this is a good enough solution for now. Can you double check that this test always runs in github actions?  There may be issues where if we ever install `transformers` as part of the integration test setup, this test will be skipped. I don't anticipate that happening though.

2022-06-27 18:08 UTC, kenxu95 commented on integration_tests/sdk/requirement_test.py
> +def default_sentiment_prediction(reviews: pd.DataFrame) -> pd.DataFrame:
can we name these clearer (its not obvious that its the reqs path that is invalid/valid):
```
sentiment_prediction_without_reqs_path()
```
and above would be:
```
sentiment_prediction_with_valid_reqs_path()
```
and `sentiment_prediction_with_invalid_reqs_path()`

2022-06-27 18:08 UTC, kenxu95 commented on sdk/aqueduct/utils.py
> +        if os.path.exists(REQUIREMENTS_FILE):
Lets not nest conditionals unnecessarily. This can be:
```
elif os.path.exists(REQUIRMENTS_FILE)
```
(and the else below would be unindented too)

2022-06-29 15:59 UTC, cw75 commented
@Fanjia-Yan reminder to update PR title to complete the sentence.

2022-06-29 22:20 UTC, merged