[1/4] Rename integration table to resource
aqueducthq/aqueduct pull request #1335
Opened 2023-05-17 20:07 UTC by kenxu95

## Describe your changes and why you are making these changes
- Changes the name of our `integration` table to be `resource`. 
- Adds a migration for this name change. 
- Updates all references to the integration table.
- Also renames all "integration" found in `lib/models` to resource, EXCEPT for any json/yaml tags like 
```
	DestResourceID uuid.UUID             `db:"dest_integration_id" json:"dest_integration_id"`
```
That means we do a follow-up migration that updates all database field references to "integration", as well as any client data structures.

## Related issue number (if any)
ENG-2780

## Loom demo (if any)

## Checklist before requesting a review
- [ ] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [ ] I have performed a self-review of my code.
- [ ] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ ] If this is a new feature, I have added unit tests and integration tests.
- [ ] I have run the integration tests locally and they are passing.
- [ ] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [ ] All features on the UI continue to work correctly.
- [ ] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

2023-05-18 15:49 UTC, saurav-c approved these changes
Is there a linear task for the JSON tag changes?

2023-05-18 15:49 UTC, saurav-c commented on src/golang/cmd/server/handler/create_table.go
> +	integrationObject *models.Resource,
Do you want to change variable names as a follow on?

2023-05-18 15:49 UTC, saurav-c commented
Also note to take a look at the DB integration tests

2023-05-18 15:51 UTC, saurav-c requested changes
@kenxu95 You'll need to replace the table name being deleted [here](https://github.com/aqueducthq/aqueduct/blob/main/src/golang/lib/repos/tests/suite.go#L111)

2023-05-18 16:02 UTC, saurav-c commented on src/golang/cmd/server/handler/create_table.go
> +	integrationObject *models.Resource,
Nvm saw follow on PR

2023-05-18 17:47 UTC, kenxu95 commented
> Is there a linear task for the JSON tag changes?

No task yet but that will be the 4th out of 5th step.

2023-05-18 19:06 UTC, likawind approved these changes

2023-05-19 23:05 UTC, saurav-c approved these changes

2023-05-22 05:39 UTC, merged