ENG 2714 Migrate get_workflow to use V2 routes
aqueducthq/aqueduct pull request #1349
Opened 2023-05-22 19:27 UTC by eunice-chan

## Describe your changes and why you are making these changes
Migrate `get_workflow` to use V2 routes to phase out the V1 routes.

## Related issue number (if any)
ENG 2714 

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [N/A] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [N/A] If this is a new feature, I have added unit tests and integration tests.
- [x] I have run the integration tests locally and they are passing.
- [ ] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [N/A] All features on the UI continue to work correctly.
- [N/A] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

2023-05-22 22:42 UTC, likawind commented on sdk/aqueduct/backend/api_client.py
> +                    # Hardcoded because not available from V2 routes
@kenxu95 what does these two field means? I doubt if they are used in workflow reading routes as I don't see them in any responses

2023-05-22 22:43 UTC, kenxu95 commented on sdk/aqueduct/backend/api_client.py
> +                    # Hardcoded because not available from V2 routes
They are only used to create artifacts on the SDK side, the backend has no concept of them.

2023-05-23 01:06 UTC, likawind commented on aq.py
> +)
remove?

2023-05-23 01:07 UTC, likawind commented on sdk/aqueduct/backend/api_client.py
> +                    # Hardcoded because not available from V2 routes
cool! I think we can just ignore these (rather than assign a default value) if possible, when reading from the backedn

2023-05-23 01:07 UTC, likawind reviewed
LGTM! @kenxu95 is integration test sufficient to capture changes on these APIs?

2023-05-23 17:32 UTC, likawind approved these changes

2023-05-23 17:40 UTC, likawind requested changes
@eunice-chan I'm requesting changes just to block the merge until release, as there's a regression on this feature, and would like to minimize the risk

2023-05-30 18:20 UTC, likawind approved these changes

2023-05-30 22:00 UTC, merged