[UI/3] ENG-1509 Add flag to Update Mode indicating which is currently used
aqueducthq/aqueduct pull request #412
Opened 2022-08-30 03:07 UTC by eunice-chan

## Describe your changes and why you are making these changes
Signify to the user which update mode is the active one (since the active workflow is currently the latest workflow).

<img width="1440" alt="update_mode_active" src="https://user-images.githubusercontent.com/30596854/187339489-4ed983c0-2677-423e-b0b9-2934d2c116a6.png">

## Related issue number (if any)
ENG-1509

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [N/A] If this is a new feature, I have added unit tests and integration tests.
- [N/A] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

2022-08-30 15:44 UTC, vsreekanti commented
@eunice-chan, this looks great! Two tiny things:
1. Showing the tooltip next to every table is a little confusing; it seems to imply that you're going to say something table-specific, but looking at the code, it looks like every tooltip will just say "Multiple updates modes have been associated with this table." That doesn't actually seem true since some of the tables only have one update mode. Maybe we could include this information somewhere else? 
2. Can we align the checkbox with the table name rather than the middle of the `Box` with the text?

2022-08-30 15:47 UTC, eunice-chan commented
@vsreekanti Thanks for your attention to detail!
> Showing the tooltip next to every table is a little confusing; it seems to imply that you're going to say something table-specific, but looking at the code, it looks like every tooltip will just say "Multiple updates modes have been associated with this table." That doesn't actually seem true since some of the tables only have one update mode. Maybe we could include this information somewhere else?

Do you think it'll be better to just have the tooltip next to the tables with multiple update modes? Or should we remove it completely? Since now we mark the active update mode, it might not really be necessary anymore.

> Can we align the checkbox with the table name rather than the middle of the Box with the text?

Yes, I can do that!

2022-08-30 15:52 UTC, vsreekanti commented
I think you're right that the tooltip is probably not necessary now. Let's remove it for the time being, and we can always add it back if it is something users are confused by in the future.

2022-08-30 20:34 UTC, eunice-chan commented
Remove tooltip & align checkbox with the start of the line (@agiron123 I think the way I aligned it is kind of bad but I can't find a cleaner way that works, so would appreciate any ideas you have)
<img width="636" alt="image" src="https://user-images.githubusercontent.com/30596854/187537654-ceaf0640-a455-44fb-b8f4-87d45ca6cb5b.png">

2022-08-30 20:42 UTC, agiron123 commented on src/ui/common/src/components/workflows/WorkflowSettings.tsx
> +                <div style={{ marginTop: '1.2em' }}>
Can you use the box component here please?

We're also not really using units like em at the moment. Our design system is based on units of 8px. 

See if you can line things up with a box and the sx prop and a marginTop of x * 8px, where x is whatever looks aligned..

2022-08-30 20:43 UTC, agiron123 commented on src/ui/common/src/components/workflows/WorkflowSettings.tsx
> +              style={{ marginTop: '-1.2em' }}
Same as below, let's try using units of 8px here.

2022-08-30 20:51 UTC, agiron123 commented
For alignment here, i'd try wrapping each of the lines in an MUI box component and set the paddingTop for each label.

You can see an example of this here:
```
      <FormControlLabel
          value="start"
          control={<Checkbox />}
          label={<Box sx={{ paddingTop: '24px' }}><Typography variant="body1">Line1 Text</Typography><Typography variant="body1">Line2Text</Typography></Box>}
          labelPlacement="start"
        />
```

Code Sandbox to play around with:
https://codesandbox.io/s/multi-line-labels-fm4sd0?file=/index.tsx

2022-08-30 20:54 UTC, agiron123 requested changes
Couple small comments, but should be easy to resolve.

2022-08-30 23:40 UTC, eunice-chan commented
Updated `div` -> `box`; `1.2em` -> `24px`. Visually looks about the same.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/30596854/187558475-5e489ca2-b481-437f-913c-0f488ae4329f.png">

2022-08-31 02:00 UTC, agiron123 approved these changes
Nice work!

2022-08-31 14:43 UTC, merged