finished implementation to avoid unnecessary get position api call
aqueducthq/aqueduct pull request #92
Opened 2022-06-11 00:19 UTC by Boyuan-Deng

### This PR:
- implement logic to only call get position call when necessary

#### Linear Discussion:
https://linear.app/aqueducthq/issue/ENG-1060/bug-dag-node-positioning-repeatedly-fetched-from-api-on-sidesheet-open

### Test:
- https://www.loom.com/share/3fad3b7d158646678922a6a7f7295518

2022-06-22 18:12 UTC, Boyuan-Deng commented
Would like a review

2022-06-22 18:34 UTC, agiron123 commented on src/ui/common/src/reducers/workflow.ts
> +    builder.addCase(handleGetSelectDagPosition.pending, (state, action) => {
Where are we storing the selectedDagPosition so that we can avoid having to refetch?

2022-06-22 18:41 UTC, agiron123 commented on src/ui/common/src/utils/reactflow.ts
> +export const getDagLayoutElements = (
Shouldn't we also move this function to a redux thunk as well?

That way we can use the state that we fetched throughout our application.

We can have getDagLayoutElements and getSelectDagPosition either as two separate calls, or just one.

2022-06-22 18:41 UTC, agiron123 commented on src/ui/common/src/reducers/workflow.ts
> +    console.log('reached handle Position');
remove log

2022-06-22 18:43 UTC, agiron123 requested changes
Nice work! Thanks for posting a demo. Really cleared things up for me.

Couple changes requested, happy to discuss later this afternoon.

2022-06-27 18:01 UTC, vsreekanti commented
@Boyuan-Deng, what is the status on this PR?

2022-06-27 18:24 UTC, Boyuan-Deng commented
> @Boyuan-Deng, what is the status on this PR?

Still working on making some changes. Waiting to meet andre after lunch for additional context around the changes

2022-06-29 23:32 UTC, cw75 commented
@Boyuan-Deng @agiron123  is this PR good?

2022-06-29 23:55 UTC, Boyuan-Deng commented
> @Boyuan-Deng @agiron123 is this PR good?

Still working on cleaning up a few things. Should be done tonight.

2022-06-30 04:26 UTC, Boyuan-Deng commented on src/ui/common/src/reducers/workflow.ts
> +      state.artifactResults = {};
https://www.loom.com/share/dbb2c6def3174031a75697ec274e9cbb
Explains why I need to set the state directly instead of calling a function

2022-06-30 17:57 UTC, agiron123 approved these changes
Nice work! Great job with these changes.

2022-06-30 22:46 UTC, merged